В этом уроке ты узнаешь, как обрабатывать исключения. Нужна конструкция **`try...catch`**.

В блок **`try`** нужно обернуть код, в котором может произойти исключение.

В блок **`catch`** нужно добавить:

- класс исключения — например, при работе с файлами можно ожидать, что файла не будет по указанному пути или у программы не будет к нему доступа. Классы знает и определяет сам разработчик;
- действие — например, вывести сообщение `"Ошибка"`.

Вот как это выглядит:
```
try {
      // опасный код, из-за которого может произойти исключение
} catch (Exception exception) { // класс исключения
      // код, который выполнится, если произойдёт исключение
} 
```

Программа читает информацию из файла. Нужно обработать исключение: оно появляется, когда указали путь до несуществующего файла.

Действие — вывести текст `"Произошла ошибка!"`. Класс для обработки ошибки — `Exception`**:**
```
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;

public class Praktikum {

    public static void main(String[] args) {
        try {
            // путь к несуществующему файлу
            Files.lines(Paths.get("Путь до несуществующего файла"), StandardCharsets.UTF_8).forEach(System.out::println);
        } catch (Exception exception) {
            System.out.println("Произошла ошибка!");
        }
    }
} 
```

Теперь код будет отлавливать все ошибки, которые произойдут в блоке.

Если изменить `Exception` на `Throwable`**,** поймаешь ещё и ошибки JVM. С одной стороны, это полезно: получится универсальное средство для всех ошибок.

С другой стороны, это слишком неконкретно. Ты не знаешь, какую именно ошибку удалось поймать и как на неё реагировать.

Что может произойти:

- программа не найдёт файл;
- программа найдёт файл, но не сможет прочитать. Например, у файла неверная кодировка.

Во всех случаях получится одна и та же надпись — `"Произошла ошибка!"`.

Так не получится сказать пользователю, что конкретно не так и что делать.

Чтобы выдавать полезные сообщения об ошибках, нужно обрабатывать конкретные исключения, а не все сразу.

Конструкция `try...catch` может обрабатывать сразу несколько исключений. Нужно добавить ещё один блок `catch`:
```
try {
      // опасный код, из-за которого может произойти исключение
} catch (ExceptionFirstType exception) {
      // код, который выполнится, если произойдёт исключение первого типа
} catch (ExceptionSecondType exception) {
      // код, который выполнится, если произойдёт исключение второго типа
} catch (ExceptionThirdType exception) {
      // код, который выполнится, если произойдёт исключение третьего типа
} 
```

Потренируйся обрабатывать конкретные исключения.

Несколько однотипных действий в блоках `catch` можно объединять в одно. Пригодится оператор `|`.

Посмотри на предыдущее задание. Программа два раза печатает сообщение `"Проблемы с доступом к файлу"`.

Вот запись с двумя `catch`:
```
try {
      // опасный код, из-за которого может произойти исключение
} catch (ExceptionFirstType exception) {
      // однотипное действие
} catch (ExceptionSecondType exception) {
      // однотипное действие
} 
```

Её можно заменить на такую:
```
try {
      // опасный код, из-за которого может произойти исключение
} catch (ExceptionFirstType | ExceptionSecondType exception) {
      // однотипное действие
} 
```

Получится:
```
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.io.IOException;
import java.nio.file.NoSuchFileException;
import java.nio.file.AccessDeniedException;

public class Praktikum {

    public static void main(String[] args) {
        try {
            Files.lines(Paths.get("Путь до несуществующего файла"), StandardCharsets.UTF_8).forEach(System.out::println);
        } catch (NoSuchFileException | AccessDeniedException exception) {
            System.out.println("Проблемы с доступом к файлу");
        } catch (IOException exception) {
            System.out.println("Неизвестная ошибка");
        }
    }

} 
```
### Задание
### 1
Добавь обработку исключений для случаев:

- файл не найден — `NoSuchFileException`;
- файл найден, но к нему нет доступа. Например, нет разрешения на чтение — `AccessDeniedException`;
- для всех остальных ошибок — `IOException`.

Для первого и второго случаев выведи текст `"Проблемы с доступом к файлу"`, а для последнего — `"Неизвестная ошибка"`.

Нужно обработать исключения в таком порядке: `NoSuchFileException`, `AccessDeniedException`, `IOException`.
Без решения
```Java
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.io.IOException;
import java.nio.file.NoSuchFileException;
import java.nio.file.AccessDeniedException;

public class Praktikum {

    public static void main(String[] args) {
        try {
            // Путь к несуществующему файлу, чтобы произошло исключение
            Files.lines(Paths.get("Путь до несуществующего файла"), StandardCharsets.UTF_8).forEach(System.out::println);
        } catch ...

        }
    }
}
```

С решением
```Java

```
