Ты уже знаешь, чем отличаются исключения и ошибки. Ошибки ломают программу полностью, а исключения — нет.

Исключения бывают **проверяемые** (англ. «checked») и **непроверяемые** (англ. «unchecked»).

### Проверяемые исключения

Проверяемые исключения — те, которые программист предусмотрел. Компилятор ожидает их увидеть.

Представь, что в программе есть файл с данными. Программист указал путь до него. Программа запустилась и оказалось, что файла по такому пути нет.

Программист предвидел, что такое может случиться. Он заранее обработал этот случай. Например, зашил в код, что нужно выдать пользователю сообщение: по указанному пути файла нет. Исключение проверяемое.

### Непроверяемые исключения

Непроверяемые исключения — те, которые программист не может предвидеть. Компилятор не понимает, что появится исключение. Значит, он его не обработает.

Часто эти исключения возникают из-за человеческого фактора.

`NullPointerException` — непроверяемое исключение. Программист забыл создать объект или присвоил ему значение `null`. А потом попытался его использовать.

Если обратиться к элементу массива по неверному индексу, тоже появится непроверяемое исключение — `ArrayIndexOutOfBoundsException`**.**

Для непроверяемых исключений есть класс `RuntimeException`. Все непроверяемые исключения наследуются от него.

Производные от `Throwable` и `Exception` будут генерировать проверяемые исключения — кроме `RunTimeExeption`.

Все ошибки — непроверяемые.

![img_1.png](img%2Fimg_1.png)

### Задание
#### 1

![img_2.png](img%2Fimg_2.png)